CREATE TABLE DAILY_LOGS (
    LOG_ID SERIAL PRIMARY KEY,
    USER_ID INT NOT NULL REFERENCES USERS (USER_ID),
    LOG_DATE DATE NOT NULL DEFAULT CURRENT_DATE,
    MEAL_TYPE SHIFT NOT NULL, -- 'lunch' or 'dinner'
    IS_SPECIAL BOOLEAN NOT NULL DEFAULT FALSE,
    SPECIAL_DISH_NAME TEXT,
    EXTRA_RICE_QTY INT NOT NULL DEFAULT 0,
    EXTRA_ROTI_QTY INT NOT NULL DEFAULT 0,
    TOTAL_COST NUMERIC(10, 2) NOT NULL,
    CREATED_AT TIMESTAMPTZ DEFAULT NOW()
);

-- Index for billing queries
CREATE INDEX IDX_DAILY_LOGS_USER_DATE ON DAILY_LOGS (USER_ID, LOG_DATE);
