CREATE TABLE INVENTORY (
	INVENTORY_ID SERIAL PRIMARY KEY,
	ITEM_ID INT NOT NULL REFERENCES PRODUCTS (ITEM_ID),
	BATCH_NO INT NOT NULL,
	QUANTITY SMALLINT NOT NULL,
	COST_PRICE NUMERIC(10, 2) NOT NULL,
	CREATED_AT TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
	UNIQUE (ITEM_ID, BATCH_NO)
);