CREATE TYPE DAY AS ENUM(
	'monday',
	'tuesday',
	'wednesday',
	'thursday',
	'friday',
	'saturday',
	'sunday'
);

CREATE TYPE SHIFT AS ENUM('lunch', 'dinner');

CREATE TABLE MENU (
	WEEKDAY DAY NOT NULL,
	MENU_TYPE SHIFT NOT NULL,
	FOOD_CLASS FOOD_CLASS NOT NULL,
	ITEM_ID INT NOT NULL,
	PRIMARY KEY (WEEKDAY, MENU_TYPE, FOOD_CLASS),
	FOREIGN KEY (ITEM_ID) REFERENCES PRODUCTS (ITEM_ID)
);

CREATE OR REPLACE FUNCTION ENFORCE_MENU_CONSTRAINTS() 
RETURNS TRIGGER AS $$
DECLARE
    prod_type ITEM_TYPE;
    prod_class FOOD_CLASS;
BEGIN
    SELECT TYPE, FOOD_CLASS INTO prod_type, prod_class
    FROM PRODUCTS
    WHERE ITEM_ID = NEW.ITEM_ID;

    IF prod_type <> 'finished_product' THEN
        RAISE EXCEPTION 'Menu item must be a finished product: ITEM_ID=%', NEW.ITEM_ID;
    END IF;

    IF prod_class <> NEW.FOOD_CLASS THEN
        RAISE EXCEPTION 'Menu food_class does not match product classification: ITEM_ID=%', NEW.ITEM_ID;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER TRG_MENU_CHECK
BEFORE INSERT OR UPDATE ON MENU
FOR EACH ROW
EXECUTE FUNCTION ENFORCE_MENU_CONSTRAINTS();