CREATE TABLE ONE_OFF_ORDERS (
    ORDER_ID      BIGSERIAL PRIMARY KEY,
    USER_ID       INT NOT NULL REFERENCES USERS(USER_ID),
    WEEKDAY       DAY NOT NULL,
    SHIFT         SHIFT NOT NULL,
    ITEM_ID       INT NOT NULL REFERENCES PRODUCTS(ITEM_ID),
    ORDER_DATE    DATE NOT NULL DEFAULT CURRENT_DATE
);
