CREATE TYPE ITEM_TYPE AS ENUM('raw_material', 'finished_product');

CREATE TYPE FOOD_CLASS AS ENUM('veg', 'non_veg');

CREATE TABLE PRODUCTS (
	ITEM_ID SERIAL PRIMARY KEY,
	NAME TEXT NOT NULL,
	TYPE ITEM_TYPE NOT NULL,
	SELLING_PRICE NUMERIC(10, 2),
	FOOD_CLASS FOOD_CLASS,
	CONSTRAINT CHK_SELLING_PRICE CHECK (
		(
			TYPE = 'finished_product'
			AND SELLING_PRICE > 0
		)
		OR (
			TYPE = 'raw_material'
			AND SELLING_PRICE IS NULL
		)
	),
	CONSTRAINT CHK_FOOD_CLASS CHECK (
		(
			TYPE = 'finished_product'
			AND FOOD_CLASS IS NOT NULL
		)
		OR (
			TYPE = 'raw_material'
			AND FOOD_CLASS IS NULL
		)
	)
);