CREATE TYPE USER_TYPE AS ENUM('normal', 'admin');

CREATE TYPE SUBSCRIPTION_TYPE AS ENUM('monthly', 'one_off');

CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	NAME TEXT,
	MOBILE_NO TEXT,
	BUILDING_NO TEXT,
	ROOM_NO TEXT,
	ROLE USER_TYPE DEFAULT 'normal',
	PLAN SUBSCRIPTION_TYPE NOT NULL
);