import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native';
 
export const THEME = {
  light: {
    background: '#F2F2F2',
    foreground: '#1A1A1A',
    card: '#FFFFFF',
    cardForeground: '#1A1A1A',
    popover: '#FFFFFF',
    popoverForeground: '#1A1A1A',
    primary: '#A6290D',
    primaryForeground: '#F2F2F2',
    secondary: '#F2AE2E',
    secondaryForeground: '#1A1A1A',
    muted: '#84BF2A',
    mutedForeground: '#666666',
    accent: '#F2811D',
    accentForeground: '#FFFFFF',
    destructive: '#A6290D',
    border: '#E0E0E0',
    input: '#E0E0E0',
    ring: '#A6290D',
    radius: '0.625rem',
    chart1: '#84BF2A',
    chart2: '#F2AE2E',
    chart3: '#F2811D',
    chart4: '#A6290D',
    chart5: '#F2F2F2',
  },
  dark: {
    background: '#1A1A1A',
    foreground: '#F2F2F2',
    card: '#2D2D2D',
    cardForeground: '#F2F2F2',
    popover: '#2D2D2D',
    popoverForeground: '#F2F2F2',
    primary: '#F2811D',
    primaryForeground: '#1A1A1A',
    secondary: '#84BF2A',
    secondaryForeground: '#1A1A1A',
    muted: '#F2AE2E',
    mutedForeground: '#999999',
    accent: '#A6290D',
    accentForeground: '#F2F2F2',
    destructive: '#A6290D',
    border: '#404040',
    input: '#404040',
    ring: '#F2811D',
    radius: '0.625rem',
    chart1: '#84BF2A',
    chart2: '#F2AE2E',
    chart3: '#F2811D',
    chart4: '#A6290D',
    chart5: '#F2F2F2',
  },
};
 
export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
};